version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: home-app
    restart: always
    ports:
      - "69:69"
    environment:
      - NODE_ENV=production
      - PORT=69
      - HOST=0.0.0.0
    networks:
      - home-network

networks:
  home-network:
    driver: bridge
