version: '3.8'

services:
  homepage:
    image: php:8.2-apache
    container_name: home
    restart: unless-stopped
    volumes:
      - ./homepage:/var/www/html
    ports:
      - "8080:80" 
    networks:
      - homepage-network

networks:
  homepage-network:
    name: homepage-network
