version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    environment:
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_HOST: mariadb
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      APP_URL: ${APP_URL}
    ports:
      - "${PORT}:80"
    depends_on:
      - mariadb
      - minio
    networks:
      - network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PHPMYADMIN_PORT: ${PHPMYADMIN_PORT}
      PMA_HOST: mariadb
      PMA_PORT: ${PMA_PORT}
      PMA_FORCE_SSL: ${PMA_FORCE_SSL}
      PMA_ABSOLUTE_URI: ${PMA_ABSOLUTE_URI}
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - network

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_HTTP_SIGNATURES: ${MINIO_HTTP_SIGNATURES}
    command: server /data --console-address ":9001"
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_ADMIN_PORT}:9001"
    volumes:
      - minio_data:/data
    networks:
      - network

volumes:
  mariadb_data:
  minio_data:

networks:
  network:
    driver: bridge
