name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and Push Docker Image
      run: |
        docker build -t ghcr.io/almomathis/home:${{ github.sha }} -t ghcr.io/almomathis/home:latest .
        docker push ghcr.io/almomathis/home:${{ github.sha }}
        docker push ghcr.io/almomathis/home:latest
