name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and Push Docker Image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/homepage:latest .
        docker push ghcr.io/${{ github.repository }}/homepage:latest
